package com.arash.entities;
// Generated Dec 11, 2015 2:14:43 AM by Hibernate Tools 4.3.1


import javax.persistence.*;

/**
 * User generated by hbm2java
 */
@Entity
@Table(name="users",catalog="mytest")
public class User  implements java.io.Serializable {


     private int id;
     private String password;
     private String username;

    public User() {
    }

    public User(String password, String username) {
       this.password = password;
       this.username = username;
    }
   
    @Id 
    @GeneratedValue
    @Column(name="id", nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

    
    @Column(name="password", nullable=false)
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }

    
    @Column(name="username", nullable=false)
    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }




}


